### ISSUE TITLE
Invalid utf8mb4 character string issue on insert

### ISSUE THREAD

**Issue by alesasnouski** [silviucpp/mysql_pool#7]
There's an issue with mysql insert binaries:
```
CREATE TABLE `test` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `conversation_id` binary(16) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

ConversationId = <<Account1:64/integer, Account2:64/integer>>.
<<0,0,0,0,0,37,175,84,0,0,0,0,0,37,175,134>>.

mysql_pool:query(pool_0, 
<<"INSERT INTO test(`id`, `conversation_id`) VALUES (?, ?)">>, [1, ConversationId]).
warning  <0.1984.0> Warning 1300: Invalid utf8mb4 character string: 'AF5400',
in INSERT INTO test(`id`, `conversation_id`) VALUES (1, '\0\0\0\0\0%¯T\0\0\0\0\0%¯')
```
So mysql_utils:quote escapes binary and mysql throws warnings on insert.

**Comment by zuiderkwast** [comment]
With prepared statements, this shouldn't happen.

With quoting, i.e. writing it within an SQL query, it's possible to write a binary string literal as `_binary '\0\0\0\0\0%¯T\0\0\0\0\0%¯'` to avoid the Unicode warning.

* https://dev.mysql.com/doc/refman/8.0/en/charset-introducer.html
* https://mariadb.com/kb/en/string-literals/

FWIW, mysql:encode/2 (in mysql-otp) has the same problem, but it's not used by mysql:query/3,4,5 (with Params). It uses prepared statements instead of quoting.

**Comment by alesasnouski** [comment]
Ok, by bad. I can confirm that decorating field values with {blob, Val} solves the problem (percona 5.7.26, percona 8+).
Just didn't want to downgrade mysql_pool or fall back to prepared statements.
Thank you.

**Comment by alesasnouski** [comment]
Should we decorate all binary fields into {blob, Val} ?
This looks like a strange solution.
But I can confirm that this fixes this issue ...

**Comment by silviucpp** [comment]
@alesasnouski For all binary fields you need to send them as {blob, Val}. Unfortunately into the driver I don't know if it's a binary or a binary string . For this reason I have this convention.
